name: postgeek_frontend
description: Flutter web frontend for PostGeek - PostgreSQL monitoring tool

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # HTTP client
  dio: ^5.3.3
  # Local storage
  shared_preferences: ^2.2.2
  # Routing
  go_router: ^12.1.1
  # Utilities
  intl: ^0.18.1
  timeago: ^3.6.0
  # UI Components
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  fl_chart: ^0.65.0
  flutter_syntax_view: ^4.0.0
  flutter_highlight: ^0.7.0
  # Syncfusion packages
  syncfusion_flutter_charts: ^27.1.48
  syncfusion_flutter_gauges: ^27.1.48
  # UI Responsiveness
  responsive_framework: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/